services:
  mysql:
    image: mysql
    ports:
      - "3307:3307"
    expose:
      - "3306"
    environment:
      - MYSQL_USER=root
      - MYSQL_PASSWORD=admin
      - MYSQL_DATABASE=mydb
      - MYSQL_ROOT_PASSWORD=admin